{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.validator
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/data.validator_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/data.validator/data.validator_{{ version }}.tar.gz
  sha256: 9dbd6a3a7b347c245c11f7b34d392d64b3cb42fc15eb3c28905f8bebfdcd0c85

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-assertr >=2.8
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-purrr
    - r-rlang
    - r-rmarkdown
    - r-shiny
    - r-shiny.semantic >=0.3.3
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-r6
    - r-assertr >=2.8
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - r-purrr
    - r-rlang
    - r-rmarkdown
    - r-shiny
    - r-shiny.semantic >=0.3.3
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('data.validator')"           # [not win]
    - "\"%R%\" -e \"library('data.validator')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=data.validator
  license: MIT
  summary: Validate dataset by columns and rows using convenient predicates inspired by 'assertr' package. Generate good looking HTML report or print console output to display in logs of your data processing pipeline.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
